# Generated by Django 5.0.1 on 2024-01-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoapp', '0003_remove_order_product_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_registration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
