# Generated by Django 5.0.1 on 2024-01-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoapp', '0004_alter_order_date_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_registration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
